### ISSUE TITLE
Add support for I18nBundle properties

### ISSUE THREAD

**Issue by ProZhar** [BlueBoxWare/LibGDXPlugin#10]
Hi. It's me again :)

Your plugin the best 🥇 

I have created 2 games using your plugin during this time:
https://play.google.com/store/apps/details?id=com.prozhar.ua.spelling&hl=en
https://play.google.com/store/apps/details?id=com.prozhar.ru.spelling&hl=en

Now I'm creating a text quest and faced with the fact that the Android Studio does not support syntax highlighting i18n bundle *.properties files.

It looks something like that one:
![001](https://user-images.githubusercontent.com/9317340/30681120-84d216cc-9eac-11e7-9443-9ea66ff521e3.png)

Perhaps you can create a normal syntax highlight? :)

It's a good idea to edit all the bundles as android strings, but to be saved as bundles (test.properties, test_fr.properties, test_uk.properties) :
![002](https://user-images.githubusercontent.com/9317340/30681439-24ebd610-9eae-11e7-9087-8cfe564f0d9d.png)

**Comment by BlueBoxWare** [comment]
Hi, I like the design the design of your games. Nice.

As soon as I have time, I will see if I can add support for .properties files.

**Comment by BlueBoxWare** [comment]
Android Studio has an editor for properties files. If you have several properties files which belong together, like for example "Messages.properties", "Messages_uk.properties", "Messages_fr_CA_", etc., and you open one of those files, there is a tab "Resource Bundle":

![Resource Bundle](https://www.jetbrains.com/help/img/idea/2017.2/bundleEditor1.png)

which opens the editor:

![Editor](https://www.jetbrains.com/help/img/idea/2017.2/bundleEditor.png)

I think the only problem with Android Studio's support for properties files is that it says that all properties are "Unused". I can propably fix that from my plugin. I'll also try to add autocompletion for I18Bundle.get("") parameters and stuff like that.
