### ISSUE TITLE
Got an error when trying to install LibGDXPlugin on Android Studio

### ISSUE THREAD

**Issue by FuriFull** [BlueBoxWare/LibGDXPlugin#11]
Good day to you @BlueBoxWare . First of all, when i am trying to install any plugins from LibGDXInspections (annotations, kotlin-runtime, etc.), i'm getting an error: "Fail to load plugin descriptor from file annotations-13.0.jar"

So i'm able to only install the LibGDXPlugin with some errors, and when i'm running AS, i'm getting this error when compiling build.graddle:

Plugin Error: LibGDX Inspections threw an uncaught NoSuchMethodError. Disable Plugin

com.gmail.blueboxware.libgdxplugin.components.VersionManager@df32fa2: kotlin.text.StringsKt.toLongOrNull(Ljava/lang/String;)Ljava/lang/Long;

Please explain how can i use it, many thx.

**Comment by BlueBoxWare** [comment]
Does this happen when you install from https://plugins.jetbrains.com/plugin/8509-libgdx-inspections (or Android Studio's plugin manager) or when you install from source?

**Comment by FuriFull** [comment]
That happens when i try to install from https://plugins.jetbrains.com/plugin/8509-libgdx-inspections. I also tried to install from source, but i've got an error when installing Grammar-Kit to Android Studio, also had problems with Plugin DevKit.

**Comment by BlueBoxWare** [comment]
And which version of the Kotlin plugin do you have installed in Android Studio?

**Comment by FuriFull** [comment]
I will try to re-install Android Studio and try to install https://plugins.jetbrains.com/plugin/8509-libgdx-inspections from the beginning

**Comment by FuriFull** [comment]
Well, i've :
1. Reinstalled Android Studio;
2. Installed Kotlin;
3. Put LibGDX Inspections 1.13 to AS plugin directory;
4. Installed only libgdxplugin_1.13.jar
Now everything should work fine? I've tried to mark uiskin.json as a LibGDX skin, but still have 
![jsontest](https://user-images.githubusercontent.com/33024736/31899220-69368da0-b85e-11e7-9ea8-fa04b9972b19.png) instead of https://github.com/BlueBoxWare/LibGDXPlugin/blob/master/images/skinCompletion.gif?raw=true

and .fnt does not load in window, just infinite Loading...

Did i do everything right or with mistakes?

**Comment by BlueBoxWare** [comment]
When you download the plugin from plugins.jetbrains.com, you get a zip file. You should not unzip it, but in Android Studio go to Settings->Plugins->"Install plugin from disk" and select the zip file you downloaded. 

But the easiest way is: Settings->Plugins->"Browse repositories" and search for "LibGDX" and install the plugin from there.

**Comment by FuriFull** [comment]
Thanks a lot, everything is fine now. That was very weird of me trying to install unzipped files... Have a nice day!
