### ISSUE TITLE
Skin JSON files can now use the simple names of classes

### ISSUE THREAD

**Issue by ProZhar** [BlueBoxWare/LibGDXPlugin#12]
Hi. With using 1.9.9-SNAPSHOT version I've got an error with new features of skins's simple names
Can you add support fo this new features?
> - Skin JSON files can now use the simple names of classes, i.e. "BitmapFont" rather than "com.badlogic.gdx.graphics.g2d.BitmapFont". Custom classes can be added by overriding Skin.getJsonLoader() and calling json.setClassTag().
> - Skin supports cascading styles in JSON. Use the "parent" property to tag another style by name to use its values as defaults. See https://github.com/libgdx/libgdx/blob/master/tests/gdx-tests-android/assets/data/uiskin.json for example.

[CHANGES](https://github.com/libgdx/libgdx/blob/master/CHANGES)
[Commit](https://github.com/libgdx/libgdx/commit/5958def180034c1f49935e59860c8fc51b8ae1df#diff-3e4cb40382a2ab5b5a683227d0d243c3)

![aa](https://user-images.githubusercontent.com/9317340/40964032-bf12ae84-68b2-11e8-8ee7-f5016592dfbe.png)

**Comment by BlueBoxWare** [comment]
Done. Simple names and the parent property should work correctly now.
