### ISSUE TITLE
Support for libgdx JSON format outside of skin

### ISSUE THREAD

**Issue by maltaisn** [BlueBoxWare/LibGDXPlugin#19]
I'm using Json to define data in my game. Is there any way to mark the files as libgdx Json (i.e no double quotes or commas needed) instead of normal Json? This is possible for skin files, could it be for generic Json files too?

**Comment by BlueBoxWare** [comment]
No, currently the plugin can only handle Json with the specific structure of skin files.

I will see if I can add general libgdx json support, that would be a useful feature. It will probably take some time to implement though.

**Comment by BlueBoxWare** [comment]
I have added support for LibGDX style JSON. To mark a file as LibGDX JSON: in the Project Window, open the context menu for the file and select `Mark as LibGDX style JSON`. If you find any issues, please let me know.

**Comment by maltaisn** [comment]
Thanks! I did the update this morning and it worked great.
