### ISSUE TITLE
libGDX branding

### ISSUE THREAD

**Issue by payne911** [BlueBoxWare/LibGDXPlugin#22]
https://libgdx.com/brand/#libgdx-name

> The name “libGDX” always starts with a lower-case ``l``, even at the beginning of a sentence. ``GDX`` is always written in upper-case letters.

I would suggest changing the name of the plugin to ``libGDX``, and adjusting the README according to the guideline.

**Comment by BlueBoxWare** [comment]
I will have to look into it, but I think IntelliJ plugins need (or are strongly advised) to start with an uppercase.

**Comment by payne911** [comment]
Fair enough.

By the way, do you ever drop by the libGDX Discord?
Not many people seemed to know about your awesome plugin despite most people using IntelliJ. I think it's possible that the community would have great ideas for you.
Feel free to ping me there. (@payne)

There's also been increased interest in rejuvenating the framework, so maybe you could even get the contributors to be interested in advertising your plugin.

**Comment by BlueBoxWare** [comment]
To be honest I don't use libGDX anymore. Not because of libGDX itself, but because I no longer do projects where it would be useful. Still, it's nice to see the increased activity around libGDX.
