### ISSUE TITLE
Possible NoClassDefFoundError caused by binary incompatible change in IntelliJ Kotlin plugin 

### ISSUE THREAD

**Issue by darthorimar** [BlueBoxWare/LibGDXPlugin#23]
Hi!

We made some binary incompatible change in the IntelliJ Kotlin plugin. Now we do not have `org.jetbrains.kotlin.idea.references.SyntheticPropertyAccessorReference.Getter` & `org.jetbrains.kotlin.idea.references.SyntheticPropertyAccessorReference.Setter` classes. That will cause `NoClassDefFoundError` on [LoopBodyChecker class](https://github.com/BlueBoxWare/LibGDXPlugin/blob/5bcdd205cafea302c91cec7698ae93ae34a63189/src/main/kotlin/com/gmail/blueboxware/libgdxplugin/inspections/kotlin/KotlinFlushInsideLoopInspection.kt#L155)  on IntelliJ IDEA with version 2020.2 and older with Kotlin plugin 1.4.20+ installed & on IntelliJ IDEA 2020.3 in which fixed version of Kotlin plugin is bundled.
To check if reference is getter or setter, consider using `SyntheticPropertyAccessorReference.getter` property.

Sorry for inconvenience.

**Comment by BlueBoxWare** [comment]
Thank you for the warning, I appreciate it.
