### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by markapptist** [BlueBoxWare/LibGDXPlugin#25]
Hi,

This is not an issue, more so question.

After installing the plugin, how do you implement it in your project? What do you need to import?
<img width="1413" alt="Screen Shot 2020-12-05 at 9 43 51 AM" src="https://user-images.githubusercontent.com/18449928/101245973-63cdbf80-36de-11eb-92b1-3cd0d0cb778c.png">

I am trying to use the original Libgdx features, such as creating a Screen class or Game class. Does this plugin allow this, or is this only for skins and UI? 

I believe the Wiki does not go into full detail for someone who is just using this for the very first time. Appreciate the help.

**Comment by BlueBoxWare** [comment]
This plugin only provides syntax highlighting, navigation, code completion and stuff like that for projects which already use LibGDX. So the plugin does not help you to add LibGDX to a project or implement features. To do that, you'll have to follow the [official LibGDX documentation](https://libgdx.badlogicgames.com/documentation/gettingstarted/Creating%20Projects.html).

**Comment by markapptist** [comment]
Okay, thank you!
