### ISSUE TITLE
Add please support for libgdx *.json files without double quotes

### ISSUE THREAD

**Issue by ProZhar** [BlueBoxWare/LibGDXPlugin#3]
![qqq](https://cloud.githubusercontent.com/assets/9317340/20930821/96718196-bbd7-11e6-87c0-061655e9450d.png)

**Comment by BlueBoxWare** [comment]
Hmm, that would probably mean turning off IntelliJ's JSON inspections for skin files. I don't know if that's possible to do from a plugin. I'll look into that.

**Comment by ProZhar** [comment]
Sorry for my English. If that probably, can you do option in your plugin like this scenario:
1. I create JSON file in normal format with double quotes
2. Your plugin have button "Convert to Libgdx's JSON"
3. After click that button it will delete all double quotes in this file or better way create copy without double quotes
P.S. And a new idea for this option, that in this file we could also see a preview colors to the left gutter of the editor for lines which contain a color string :)

**Comment by ProZhar** [comment]
Thanks, you are the best :1st_place_medal:  :)
Just testing your new feature for skins. Want to show you that i see:
1. When 1st open, Android Studio ask me about the libgdx's skin, i choose Yes and see:
![1](https://cloud.githubusercontent.com/assets/9317340/21422840/75e5a458-c842-11e6-90c2-26c1de5dad34.png)
2. Comments are good too in just opened file:
![2](https://cloud.githubusercontent.com/assets/9317340/21422981/38f93b3a-c843-11e6-9858-9efc8bca14b4.png)

2.1. But if I click` Ctrl+/` or `Ctrl+Shift+/` nothing happening (!!! not work button combinations):
![3](https://cloud.githubusercontent.com/assets/9317340/21423113/f4f3ea38-c843-11e6-8e42-5b582594ab15.png)

2.2. If I remove `//` manually, all good (!!! but curly braces still gray, not white):
![4](https://cloud.githubusercontent.com/assets/9317340/21423511/1a615fc4-c846-11e6-8aaa-55e2e8426677.png)

2.3. And then I put again manually comment's `//` (text are not change color to grey):
![5](https://cloud.githubusercontent.com/assets/9317340/21423593/87b96d6e-c846-11e6-8b84-7f744f1f8a42.png)

2.4. After that I remove all `//` manually, and scroll up and down the file several times. Some curly braces repainted gray and some white:
![6](https://cloud.githubusercontent.com/assets/9317340/21423751/683976d6-c847-11e6-85b0-96f3f0b5d7b3.png)

2.5. Then i add all '//' manually again and some text repaint to grey, some still color. Curly braces automatically repainted to gray every row when I adding comment '//' manually:
![7](https://cloud.githubusercontent.com/assets/9317340/21424000/b0e1c996-c848-11e6-8f52-8246a6bbf8cb.png)


But in any case - thanks. It was convenient, that does not show the errors in the file.

**Comment by BlueBoxWare** [comment]
The issues should be fixed now.

**Comment by ProZhar** [comment]
Just updated the plugin and restarted Studio 2 times:
![default](https://cloud.githubusercontent.com/assets/9317340/21569456/942b8a48-cec5-11e6-9402-5ce18c0fcba0.png)
![2](https://cloud.githubusercontent.com/assets/9317340/21569457/942bc5b2-cec5-11e6-84ac-c999d2f8ddea.png)

**Comment by ProZhar** [comment]
Just update your plugin to 1.4.1
Everything works well, code highlighting are wonderful:
![8](https://cloud.githubusercontent.com/assets/9317340/21578159/c5344026-cf7e-11e6-99d1-46261f27d461.png)

Only one thing is not working - support folders for font files:
![9](https://cloud.githubusercontent.com/assets/9317340/21578200/efba5e92-cf7f-11e6-95fc-9f543364f789.png)

I want to wish you a Happy New Year. And thanks you fir this good plugin ^)

**Comment by BlueBoxWare** [comment]
Happy New Year to you too!

I'll fix the folder thing in the next update. You can also put the filename in quotes
