### ISSUE TITLE
"No documentation found" on Ctrl+Q when plugin is enabled

### ISSUE THREAD

**Issue by jfriemel** [BlueBoxWare/LibGDXPlugin#35]
#### Description

The current version of the plugin seems to mess with IntelliJ's quick documentation feature. When the plugin is enabled, no information is shown when hovering over variables and Ctrl+Q only shows "No documentation found".

#### Versions

IntelliJ: 2023.1 (Ultimate Edition), Build #IU-231.8109.175
LibGDX Plugin: 1.24.3

#### Screenshots

Expected:
<img src="https://user-images.githubusercontent.com/58466983/230479321-3f7b4008-23ad-482a-88fc-466713f25c58.png" width=50% height=50%>
Actual:
<img src="https://user-images.githubusercontent.com/58466983/230479356-c3f9c614-a168-4c30-9119-00068af380f0.png" width=50% height=50%>

**Comment by jeffcragg** [comment]
Absolutely this and its a nightmare to work out as well.

**Comment by BlueBoxWare** [comment]
Thanks for the report! It should be fixed now.

**Comment by jfriemel** [comment]
Yes, it works again. Thanks for the quick fix!
