### ISSUE TITLE
Gutter Color display support for hexadecimal Color(int) constructor

### ISSUE THREAD

**Issue by SomeTroglodyte** [BlueBoxWare/LibGDXPlugin#37]
One invalid Color constructor is recognized as displayable Color, while the best valid one is not:
![image](https://github.com/BlueBoxWare/LibGDXPlugin/assets/63000004/bdef6847-9d30-497c-b890-6775a1c587e3)

The decimal notation for Color(int) does work, only the more useful hex one does not.
If that has internal reasons - idea - how about supporting specific a comment syntax? I would add `// #5300FFFF` to the line to specifically force a color display in the gutter...

**Comment by BlueBoxWare** [comment]
Thanks for the bug report!
