### ISSUE TITLE
Include screen shots in README file

### ISSUE THREAD

**Issue by czyzby** [BlueBoxWare/LibGDXPlugin#4]
I think it would make people much more likely to install this plugin once they see screen shots and gifs of all most significant code inspections and editors. For example, I had a "whoa" moment once I saw [this](https://cloud.githubusercontent.com/assets/9317340/21578159/c5344026-cf7e-11e6-99d1-46261f27d461.png). As I'm writing this, the README doesn't even seem to mention a full fledged skin JSON editor.

Anyway, I added info about this plugin in [gdx-skins](https://github.com/czyzby/gdx-skins). It might not seem like much, but out of my LibGDX-related projects, it's definitely the most popular one (getting about 200-400 views each day, mostly through Google) - I hope it influences your traffic at least a little bit.

**Comment by BlueBoxWare** [comment]
Thanks for adding the plugin to gdx-skins!

Yeah, the current README is not good. I'll create a more comprehensive and up to date one in the next few days.

**Comment by czyzby** [comment]
Already looks much better. I think this issue can be closed, unless you still want to work on the README file.

**Comment by BlueBoxWare** [comment]
Yes, closing it
