### ISSUE TITLE
Autocomplite fo Skin.getDrawable()

### ISSUE THREAD

**Issue by ProZhar** [BlueBoxWare/LibGDXPlugin#7]
Is it possible to add autocomplite for Skin.getDrawable() like this for *.java files?
![autocomplite111](https://cloud.githubusercontent.com/assets/9317340/23213464/b07025f6-f913-11e6-83ea-43115c8e038d.png)

**Comment by BlueBoxWare** [comment]
It is now possible to get autocomplete for Skin (and TextureAtlas) get methods, but you have to use an annotation to specify the files from which to get the names to use, as described [here](https://github.com/BlueBoxWare/LibGDXPlugin#skin-resources-and-atlas-region-names-in-java-and-kotlin-code)
