### ISSUE TITLE
Add support for array of colors

### ISSUE THREAD

**Issue by ProZhar** [BlueBoxWare/LibGDXPlugin#8]
1. I have some colors:
![01](https://cloud.githubusercontent.com/assets/9317340/24330644/de6cf96c-122b-11e7-8a21-3e664fec4bb0.png)
2. I have some array of colors within style class:
![02](https://cloud.githubusercontent.com/assets/9317340/24330650/23d3aece-122c-11e7-9a61-14100e2daa35.png)
3. In skin.json (no preview, no "jump to source" (Ctrl-B)) :
![03](https://cloud.githubusercontent.com/assets/9317340/24330699/0488f244-122d-11e7-9298-f6d2daaccd78.png)

**Comment by ProZhar** [comment]
Still not working
![04](https://cloud.githubusercontent.com/assets/9317340/24749237/fbca5a52-1aca-11e7-820f-215124405003.png)

![05](https://cloud.githubusercontent.com/assets/9317340/24749245/01f7c522-1acb-11e7-892c-d6b0f773e569.png)

**Comment by BlueBoxWare** [comment]
I didn't publish the version with this fix to plugins.jetbrains.com yet. But it should be available now.
